[package]
name = "mylist"
version = "0.1.0"
authors = ["fuliangliang <fuliangliang@oppo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
